### ISSUE TITLE
Tornillo de final de carrera de eje Z está flojo

### ISSUE THREAD

**Issue by aguadopd** [GERUNSJ/Fuga3D#10]
El tornillo que permite ajustar la altura de final de carrera en el eje Z está flojo, y eso hace que deba calibrarse la altura en cada impresión. Creemos que si mejoramos esto, el ajuste va a ser menos frecuente.

**Comment by aguadopd** [comment]
Lo solucionamos con unas vueltas de teflón. Con el uso veremos si fue ha sido una solución efectiva. Dejo abierto esto hasta que lo verifiquemos.

![img_20171201_174546 redimensionado](https://user-images.githubusercontent.com/5558299/33520576-95e9fa32-d79c-11e7-90fa-316f25af33ad.jpg)

**Comment by MauroDiamantino** [comment]
> Lo solucionamos con unas vueltas de teflón. Con el uso veremos si fue ha sido una solución efectiva. Dejo abierto esto hasta que lo verifiquemos.
> 
> ![img_20171201_174546 redimensionado](https://user-images.githubusercontent.com/5558299/33520576-95e9fa32-d79c-11e7-90fa-316f25af33ad.jpg)

Luego de varias impresiones se comprobó que esta solución ha sido bastante buena, ya que cada vez que se re-niveló la cama se encontró que la nivelación no había cambiado demasiado.
