### ISSUE TITLE
Resistencia calefactora y sensor de temperatura no están sujetos a bloque de _hotend_

### ISSUE THREAD

**Issue by aguadopd** [GERUNSJ/Fuga3D#12]
Luego de cambiar partes del _hotend_ (ver #9), la resistencia calefactora y el sensor de temperatura quedaron sueltos en el bloque, y por tanto no se puede imprimir. 

Dijo Checho que el tornillo del bloque está robado, por lo que algunas soluciones posibles pueden ser:

- Intentar poner un tornillo del paso correcto. Puede haber en el tarrito de vidrio (mermelada) que tiene cosas de impresora.
- Intentar poner un tornillo de paso más grande que el nominal, así sin roscar nada.
- Hacer una rosca con un macho roscante y poner un tornillo más grande que el nominal
- Sujetar todo con pegamento de alta temperatura.

Esta última opción es la más fácil y la que habíamos hecho antes. No presenta problemas hasta que se quiere sacar todo por alguna razón.

**Comment by MauroDiamantino** [comment]
Se solucionaron ambos problemas. La resistencia calefactora se fijó al hotend colocando un tornillo roscachapa de diámetro adecuado, de modo que al enroscarlo fuera haciendo la rosca sobre el hotend. Por otro lado, el sensor de temperatura se fijó con Fastix de alta temperatura (rojo). Luego de varias pruebas, se comprobó que ambos habían quedado adecuadamente fijados.
