### ISSUE TITLE
Se junta plástico en la parte superior del _nozzle_ del _hotend_

### ISSUE THREAD

**Issue by aguadopd** [GERUNSJ/Fuga3D#5]
Al parecer la punta cuadrada (_nozzle_), que es por donde sale el plástico y donde se conecta la resistencia calefactora y el termistor, está desajustado, ya que se junta plástico derretido en la superficie superior de ese prisma rectangular. 

Desconozco el modelo del _hotend_ y por tanto no puedo dar más detalles. 

- [x] Averiguar más con los que saben.

**Comment by german-e-mas** [comment]
Se sigue juntando plástico?

**Comment by aguadopd** [comment]
Vigente.

Sacamos el _hotend_ entero y no pudimos desajustar el bloque. Al parecer se ha robado el tornillo hueco que conecta las partes (_barrel_).

![imagen](https://user-images.githubusercontent.com/5558299/30766828-21b53e7a-9fce-11e7-942e-a9c72326b6b9.png)
_Nota: nuestro hotend es de metal puro, no tiene tubo de teflón adentro_

La boquilla no ha estado bien ajustada y entonces el plástico caliente se mete por ese espacio, fluye por la rosca y sale por la parte de arriba del bloque. Creo que no podemos ajustar bien la boquilla porque hay plástico en las roscas. Habría que intentar ajustar la boquilla con el _hotend_ caliente, pero estando robado el _barrel_, tal vez convendría comprar un nuevo hotend, entero.

**Comment by aguadopd** [comment]
Solucionado con #9.

**Comment by aguadopd** [comment]
![img_20171201_161725 redimensionado](https://user-images.githubusercontent.com/5558299/33520988-33790a02-d7a4-11e7-809b-d7c8123e041c.jpg)
Acá se aprecia un poco mejor el problema que teníamos. En impresiones largas, esas gotas empezaba a tocar la punta y arruinar la impresión, si no se sacaban a tiempo.
