### ISSUE TITLE
Reemplazar hotend con repuesto

### ISSUE THREAD

**Issue by aguadopd** [GERUNSJ/Fuga3D#9]
Checho trajo un _hotend_ usado que tenía. Es el mismo modelo que el que está puesto: Hexagon. Lo dejo adentro de la impresora. Tiene la punta rota, así que hay que ponerle la punta vigente.

A hacer:

0. Sacar filamento. Para ello, calentar, extruir un poquito y luego tirar hacia arriba para sacar todo.
1. Calentar hotend actual a xxx °C
2. Agarrar bloque con una pinza y aflojar punta con una llave.
3. Enfriar y sacar hotend. Despegar termistor y resistencia calefactora.
4. Poner nuevo hotend y fijar resistencia y termistor.
5. Calentar bloque y sacar punta.
6. Poner nueva punta vieja.

Con esto solucionamos #7 y #5.

[Acá](https://youtu.be/tDq1Du9gaWM?t=4m50s) hay un poco de información.

**Comment by aguadopd** [comment]
Con Julio sacamos filamento. Para ello (siguiendo https://youtu.be/t7ZNByjHgFk?t=2m28s) liberamos el mecanismo que presiona el filamento contra el tornillo moleteado, con el fin de poder tirar o empujar a mano.
Calentamos a 200°, empujamos para que extruya un poco y luego tiramos rápidamente hacia arriba.

![img_20171201_161250 redimensionado](https://user-images.githubusercontent.com/5558299/33520311-5c6c7b86-d797-11e7-8dd5-44fdc0cb9a08.jpg)

**Comment by aguadopd** [comment]
Con el _hotend_ a 200°C, sostenemos el bloque con una pinza y desajustamos la punta con otra. No es difícil, más sí incómodo.

![img_20171201_161726 redimensionado](https://user-images.githubusercontent.com/5558299/33520338-e3229a8e-d797-11e7-8c0c-d90026d38562.jpg)

**Comment by aguadopd** [comment]
Sacamos el _hotend_, luego de sacar el ventilador que enfría al disipador y el plástico que sostiene al conjunto. 
![img_20171201_162409 redimensionado](https://user-images.githubusercontent.com/5558299/33520357-37d6ff02-d798-11e7-95b4-1bd3f186c9ba.jpg)
![img_20171201_162528 redimensionado](https://user-images.githubusercontent.com/5558299/33520358-38091118-d798-11e7-8d3a-2df6813705f5.jpg)
![img_20171201_162543 redimensionado](https://user-images.githubusercontent.com/5558299/33520359-4111f6a8-d798-11e7-84b4-daa8fa3175ff.jpg)

**Comment by aguadopd** [comment]
La resistencia calefactora y el sensor de temperatura están sujetos al bloque con pegamento de alta temperatura, por lo que es difícil sacarlos. Sacamos el pegamento y escarbamos un poco para sacar el sensor. La resistencia necesitó ayuda mecánica.

![img_20171201_162809 redimensionado](https://user-images.githubusercontent.com/5558299/33520384-a7656c28-d798-11e7-812e-380a8d4676bd.jpg)
![img_20171201_163450 redimensionado](https://user-images.githubusercontent.com/5558299/33520385-a7a0a266-d798-11e7-932f-d330720b839f.jpg)


![img_20171201_162806 redimensionado](https://user-images.githubusercontent.com/5558299/33520383-a72457c4-d798-11e7-8bef-43a73dce4820.jpg)

**Comment by aguadopd** [comment]
Suponemos que el tornillo que ajusta el _barrel_ del nuevo _hotend_ está ajustado (si es que hay tornillo). Continuamos así:

1. Colocamos el nuevo _hotend_ en la impresora.
2. Calentamos a 220°C (al parecer lo máximo que se puede llegar antes de que largue un error porque la temperatura no se incrementa --¿thermal rundown?--).
3. Sacamos la punta del _hotend_ nuevo.
4. Ponemos la punta del _hotend_ viejo. Ajustamos bien pero sin ejercer mucha fuerza.

Al parecer lo de calentar a lo máximo posible tolerado por el _hardware_ disponible ayuda a un mejor ajuste por temas de contracción y dilatación. Así se evita que luego aparezcan espacios entre _barrel_ y punta por los cuales se puede filtrar el plástico (ver dibujo en #5).

[Acá](https://youtu.be/tDq1Du9gaWM?t=4m50s) hay una explicación, tiene subtítulos.

![img_20171201_171543 redimensionado](https://user-images.githubusercontent.com/5558299/33520479-6965445a-d79a-11e7-8059-24f0f2d43ae3.jpg)

**Comment by aguadopd** [comment]
La punta quedó bien. El único problema ahora es que tanto el sensor como la resistencia calentadora se salen de sus orificios, pero para eso creo nuevo _issue_. Julio hizo una prueba sosteniendo a ambos con cinta (desde sus cables) y reporta una buena impresión sin pérdidas de plástico ---hasta que se salió el sensor---. Así que vamos a suponer que la operación fue exitosa.

Closes #5 #7 #9

![img_20171201_171955 redimensionado](https://user-images.githubusercontent.com/5558299/33520538-906a2aa6-d79b-11e7-91d8-b3e178deea07.jpg)

**Comment by aguadopd** [comment]
[Acá](https://www.my-home-fab.de/en/documentations/tutorials/assembling-a-hexagon-hotend) dice que "_Hexagon Hotends tend to be leaky, when they are hot_", y le pone teflón a la rosca. ¿Será la solución? Habría que desarmar todo y limpiarlo. Opto por ajustar nomás.

**Comment by german-e-mas** [comment]
Había sido ajustado antes, o no quedó bien ajustado?

Se prueba de nuevo, y sino, teflón.

**Comment by aguadopd** [comment]
Al parecer no quedó bien ajustado. Procedimiento a realizar pronto: sacar el hotend de su cubículo y ajustar afuera con 2 pinzas, pero con la resistencia calefactora conectada.

**Comment by aguadopd** [comment]
![img_20180406_195319](https://user-images.githubusercontent.com/5558299/39061115-aff9039a-4499-11e8-8d09-ea9ace75bc70.jpg)

Le pusimos teflón a la rosca inferior del _barrel_. Luego la ajustamos con las herramientas que teníamos. El procedimiento no es el correcto porque estamos agarrando el disipador y no el barrel. Sin embargo, no teníamos una llave fina que entre ahí. Agarrar el disipador también ajusta el barrel dentro del disipador, pero podemos hacer fuerza en exceso y dañar la rosca interna del disipador.

![img_20180406_195904](https://user-images.githubusercontent.com/5558299/39061407-7f7556f0-449a-11e8-8603-5abc91791a34.jpg)

Ya no junta plástico. Queda resuelto esto y #5.
